game: road_runner
no_gym: yes
step_no: 100000
seed: 666

double: yes

lr: 0.00025
update_freq: 4
epsilon_steps: 1000000
epsilon_end: 0.01
target_update: 30000

learn_start: 0
mem_size: 100000
log_freq: 250

test_freq: 25001
test_steps: 12500
test_epsilon: 0.01

mem_device: cuda
async_eval: no
async_memory: no
async_update: no
pinned_memory: no
